services:
  db:
    image: "db-nginx:${DATABASE_TAG}"
    build: database
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=database.local.com
     - NGINX_PORT=80
  be:
    image: "be-nginx:${BACKEND_TAG}"
    build: backend
    ports:
     - "8081:80"
    environment:
     - NGINX_HOST=backend.local.com
     - NGINX_PORT=80
  fe:
    image: "fe-nginx:${FRONTEND_TAG}"
    build: frontend
    ports:
     - "8082:80"
    environment:
     - NGINX_HOST=frontend.local.com
     - NGINX_PORT=80
    develop:
      watch:
        - action: sync
          path: frontend/html
          target: /usr/share/nginx/html
