services:
  db:
    image: "bigmauri/db-nginx:dev-${DATABASE_TAG}"
    build: database
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=database.local.com
     - NGINX_PORT=80
    networks:
      - poc-docker-flow-nw
  be:
    image: "bigmauri/be-nginx:dev-${BACKEND_TAG}"
    build: backend
    ports:
     - "8081:80"
    environment:
     - NGINX_HOST=backend.local.com
     - NGINX_PORT=80
    networks:
      - poc-docker-flow-nw
  fe:
    image: "bigmauri/fe-nginx:dev-${FRONTEND_TAG}"
    build: frontend
    ports:
     - "8082:80"
    environment:
     - NGINX_HOST=frontend.local.com
     - NGINX_PORT=80
    networks:
      - poc-docker-flow-nw

networks:
  poc-docker-flow-nw:
    driver: bridge
