name: "[CI] Docker Build & Push"

on:
  push:
    branches:
      - "master"
      - "develop"

run-name: "Run on ${{ github.ref_name }} - '${{ github.event.head_commit.message }}'"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Replace placeholder in .env.${{ github.ref_name }} with commit SHA
        run: sed -i "s/latest/$(echo ${{ github.sha }} | cut -c1-7)/g" _environment/.env.${{ github.ref_name }}
  
      - name: Build Docker images
        run: sh ${{ github.ref_name }}.build.sh
  
      - name: Docker Images
        run: docker images

      - name: Push Docker images
        run: sh ${{ github.ref_name }}.publish.sh
        
  test-automation:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Replace placeholder in .env.${{ github.ref_name }} with commit SHA
        run: sed -i "s/latest/$(echo ${{ github.sha }} | cut -c1-7)/g" _environment/.env.${{ github.ref_name }}

      - name: Test Docker images
        run: sh ${{ github.ref_name }}.test.sh
